/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PrePropostaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PrePropostaApiTests
    {
        private PrePropostaApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PrePropostaApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrePropostaApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PrePropostaApi
            //Assert.IsInstanceOfType(typeof(PrePropostaApi), instance, "instance is a PrePropostaApi");
        }

        
        /// <summary>
        /// Test PrePropostasPost
        /// </summary>
        [Test]
        public void PrePropostasPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string accessToken = null;
            //byte[] xAuthorization = null;
            //string codigoLoja = null;
            //string codigoLojista = null;
            //PreProposta preProposta = null;
            //var response = instance.PrePropostasPost(clientId, accessToken, xAuthorization, codigoLoja, codigoLojista, preProposta);
            //Assert.IsInstanceOf<InclusaoPrePropostaResponse> (response, "response is InclusaoPrePropostaResponse");
        }
        
    }

}
