/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPrePropostaApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>InclusaoPrePropostaResponse</returns>
        InclusaoPrePropostaResponse PrePropostasPost (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>ApiResponse of InclusaoPrePropostaResponse</returns>
        ApiResponse<InclusaoPrePropostaResponse> PrePropostasPostWithHttpInfo (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>Task of InclusaoPrePropostaResponse</returns>
        System.Threading.Tasks.Task<InclusaoPrePropostaResponse> PrePropostasPostAsync (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>Task of ApiResponse (InclusaoPrePropostaResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<InclusaoPrePropostaResponse>> PrePropostasPostAsyncWithHttpInfo (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PrePropostaApi : IPrePropostaApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PrePropostaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PrePropostaApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrePropostaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PrePropostaApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>InclusaoPrePropostaResponse</returns>
        public InclusaoPrePropostaResponse PrePropostasPost (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta)
        {
             ApiResponse<InclusaoPrePropostaResponse> localVarResponse = PrePropostasPostWithHttpInfo(clientId, accessToken, xAuthorization, codigoLoja, codigoLojista, preProposta);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>ApiResponse of InclusaoPrePropostaResponse</returns>
        public ApiResponse< InclusaoPrePropostaResponse > PrePropostasPostWithHttpInfo (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta)
        {
            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new ApiException(400, "Missing required parameter 'clientId' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'accessToken' is set
            if (accessToken == null)
                throw new ApiException(400, "Missing required parameter 'accessToken' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'codigoLoja' is set
            if (codigoLoja == null)
                throw new ApiException(400, "Missing required parameter 'codigoLoja' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'codigoLojista' is set
            if (codigoLojista == null)
                throw new ApiException(400, "Missing required parameter 'codigoLojista' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'preProposta' is set
            if (preProposta == null)
                throw new ApiException(400, "Missing required parameter 'preProposta' when calling PrePropostaApi->PrePropostasPost");

            var localVarPath = "/pre-propostas";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (clientId != null) localVarHeaderParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // header parameter
            if (accessToken != null) localVarHeaderParams.Add("access_token", Configuration.ApiClient.ParameterToString(accessToken)); // header parameter
            if (xAuthorization != null) localVarHeaderParams.Add("x-authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (codigoLoja != null) localVarHeaderParams.Add("codigoLoja", Configuration.ApiClient.ParameterToString(codigoLoja)); // header parameter
            if (codigoLojista != null) localVarHeaderParams.Add("codigoLojista", Configuration.ApiClient.ParameterToString(codigoLojista)); // header parameter
            if (preProposta != null && preProposta.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(preProposta); // http body (model) parameter
            }
            else
            {
                localVarPostBody = preProposta; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PrePropostasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InclusaoPrePropostaResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InclusaoPrePropostaResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InclusaoPrePropostaResponse)));
        }

        /// <summary>
        ///  Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>Task of InclusaoPrePropostaResponse</returns>
        public async System.Threading.Tasks.Task<InclusaoPrePropostaResponse> PrePropostasPostAsync (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta)
        {
             ApiResponse<InclusaoPrePropostaResponse> localVarResponse = await PrePropostasPostAsyncWithHttpInfo(clientId, accessToken, xAuthorization, codigoLoja, codigoLojista, preProposta);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Esta API tem o objetivo de incluir uma análise de dados sobre uma pré-proposta de crédito. Caso o cliente já possua uma proposta em andamento, ou qualquer outra inconsistência na inclusão, o sistema irá retornar um código de erro informando o motivo. Caso seja aprovada, uma proposta será incluída.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clientId">Client ID disponibilizado na criação da App.</param>
        /// <param name="accessToken">Access Token com permissões de acesso.</param>
        /// <param name="xAuthorization">base64 do codigoParceiro:codigoUsuario:senha.</param>
        /// <param name="codigoLoja">Código da loja (Filial). (fixo informada pela financeira).</param>
        /// <param name="codigoLojista">Código do lojista (Rede de loja). (fixo informada pela financeira).</param>
        /// <param name="preProposta">Pré-Proposta a ser analisada, cujo resultado, quando aprovada é uma proposta.</param>
        /// <returns>Task of ApiResponse (InclusaoPrePropostaResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<InclusaoPrePropostaResponse>> PrePropostasPostAsyncWithHttpInfo (string clientId, string accessToken, byte[] xAuthorization, string codigoLoja, string codigoLojista, PreProposta preProposta)
        {
            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new ApiException(400, "Missing required parameter 'clientId' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'accessToken' is set
            if (accessToken == null)
                throw new ApiException(400, "Missing required parameter 'accessToken' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'xAuthorization' is set
            if (xAuthorization == null)
                throw new ApiException(400, "Missing required parameter 'xAuthorization' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'codigoLoja' is set
            if (codigoLoja == null)
                throw new ApiException(400, "Missing required parameter 'codigoLoja' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'codigoLojista' is set
            if (codigoLojista == null)
                throw new ApiException(400, "Missing required parameter 'codigoLojista' when calling PrePropostaApi->PrePropostasPost");
            // verify the required parameter 'preProposta' is set
            if (preProposta == null)
                throw new ApiException(400, "Missing required parameter 'preProposta' when calling PrePropostaApi->PrePropostasPost");

            var localVarPath = "/pre-propostas";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (clientId != null) localVarHeaderParams.Add("client_id", Configuration.ApiClient.ParameterToString(clientId)); // header parameter
            if (accessToken != null) localVarHeaderParams.Add("access_token", Configuration.ApiClient.ParameterToString(accessToken)); // header parameter
            if (xAuthorization != null) localVarHeaderParams.Add("x-authorization", Configuration.ApiClient.ParameterToString(xAuthorization)); // header parameter
            if (codigoLoja != null) localVarHeaderParams.Add("codigoLoja", Configuration.ApiClient.ParameterToString(codigoLoja)); // header parameter
            if (codigoLojista != null) localVarHeaderParams.Add("codigoLojista", Configuration.ApiClient.ParameterToString(codigoLojista)); // header parameter
            if (preProposta != null && preProposta.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(preProposta); // http body (model) parameter
            }
            else
            {
                localVarPostBody = preProposta; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PrePropostasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<InclusaoPrePropostaResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (InclusaoPrePropostaResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(InclusaoPrePropostaResponse)));
        }

    }
}
